# Generated by Django 4.1.5 on 2024-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_rename_elocategories_elocategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderconfig',
            name='id',
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='IP',
            field=models.CharField(default='127.0.0.1', max_length=15, primary_key=True, serialize=False),
        ),
    ]
