# Generated by Django 4.1.5 on 2024-09-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_remove_folderconfig_id_folderconfig_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folderconfig',
            old_name='base_folder',
            new_name='local_folder',
        ),
    ]
