# Generated by Django 4.1.5 on 2024-09-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0004_rename_base_folder_folderconfig_local_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folderconfig',
            old_name='zip_sub_folder',
            new_name='big_folder',
        ),
    ]
