# Generated by Django 4.1.5 on 2024-09-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_remove_folderconfig_unzip_sub_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFolderConfig',
            fields=[
                ('IP', models.CharField(default='127.0.0.1', max_length=15, primary_key=True, serialize=False)),
                ('local_folder', models.CharField(max_length=64)),
                ('big_folder', models.CharField(max_length=64)),
                ('target_folder', models.CharField(default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Base Folder Configuration',
                'verbose_name_plural': 'Base Folder Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='folderconfig',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='folderconfig',
            name='big_folder',
        ),
        migrations.RemoveField(
            model_name='folderconfig',
            name='local_folder',
        ),
        migrations.RemoveField(
            model_name='folderconfig',
            name='target_folder',
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='archive_folder',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='commented_folder',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='download_folder',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='id',
            field=models.CharField(default='PROD', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='reduced_folder',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='split_folder',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='unzip_folder',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='folderconfig',
            name='workflow_folder',
            field=models.CharField(default='', max_length=32),
        ),
    ]
