# Generated by Django 4.1.5 on 2024-09-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_basefolderconfig_remove_folderconfig_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folderconfig',
            old_name='id',
            new_name='env',
        ),
    ]
