# Generated by Django 4.1.5 on 2024-09-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_rename_id_folderconfig_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_year', models.SmallIntegerField()),
                ('last_month', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'LICHESS Last File',
                'verbose_name_plural': 'LICHESS Last File',
            },
        ),
        migrations.AlterField(
            model_name='lichessfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Download'), (1, 'Unzipped'), (2, 'ECO-Split'), (3, 'Filtered'), (4, 'Workflow processed'), (5, 'Archived')]),
        ),
    ]
