# Generated by Django 4.1.5 on 2024-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0009_lichessstatus_alter_lichessfile_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichessstatus',
            options={'verbose_name': 'LICHESS Config', 'verbose_name_plural': 'LICHESS Config'},
        ),
        migrations.AddField(
            model_name='lichessstatus',
            name='base_url',
            field=models.URLField(default='https://database.lichess.org/'),
        ),
    ]
