# Generated by Django 4.1.5 on 2024-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_lichessstatus_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichessstatus',
            name='pattern',
            field=models.CharField(default='lichess_db_standard_rated_<YEAR>-<MONTH>.pgn.zst', max_length=64),
        ),
    ]
