# Generated by Django 4.1.5 on 2024-09-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0013_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='config_folder',
            field=models.CharField(default='', max_length=32),
        ),
    ]
