# Generated by Django 4.1.5 on 2024-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EloCategories',
            fields=[
                ('elo_cat_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('low', models.SmallIntegerField()),
                ('high', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FolderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_folder', models.CharField(max_length=192)),
                ('zip_sub_folder', models.CharField(max_length=32)),
                ('unzip_sub_folder', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='LichessFiles',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Download'), (1, 'Unzipped'), (2, 'ECO-Split'), (3, 'Filtered'), (4, 'DB-Update')])),
            ],
        ),
    ]
