# Generated by Django 4.1.5 on 2024-09-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFolderConfig',
            fields=[
                ('IP', models.CharField(default='127.0.0.1', max_length=15, primary_key=True, serialize=False)),
                ('local_folder', models.CharField(max_length=64)),
                ('big_folder', models.CharField(max_length=64)),
                ('target_folder', models.CharField(default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Base Folder Configuration',
                'verbose_name_plural': 'Base Folder Configuration',
            },
        ),
        migrations.CreateModel(
            name='EloCategory',
            fields=[
                ('elo_cat_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('low', models.SmallIntegerField()),
                ('high', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'ELO Category',
                'verbose_name_plural': 'ELO Categories',
            },
        ),
        migrations.CreateModel(
            name='FolderConfig',
            fields=[
                ('env', models.CharField(default='PROD', max_length=4, primary_key=True, serialize=False)),
                ('download_folder', models.CharField(default='', max_length=32)),
                ('unzip_folder', models.CharField(default='', max_length=32)),
                ('split_folder', models.CharField(default='', max_length=32)),
                ('commented_folder', models.CharField(default='', max_length=32)),
                ('reduced_folder', models.CharField(default='', max_length=32)),
                ('archive_folder', models.CharField(default='', max_length=32)),
                ('workflow_folder', models.CharField(default='', max_length=32)),
            ],
            options={
                'verbose_name': 'Folder Configuration',
                'verbose_name_plural': 'Folder Configuration',
            },
        ),
        migrations.CreateModel(
            name='LichessFile',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Download'), (1, 'Unzipped'), (2, 'ECO-Split'), (3, 'Filtered'), (4, 'Workflow processed'), (5, 'Archived')])),
            ],
            options={
                'verbose_name': 'LICHESS File',
                'verbose_name_plural': 'LICHESS Files',
            },
        ),
        migrations.CreateModel(
            name='LichessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_year', models.SmallIntegerField()),
                ('last_month', models.SmallIntegerField()),
                ('base_url', models.URLField(default='https://database.lichess.org/')),
                ('pattern', models.CharField(default='lichess_db_standard_rated_<YEAR>-<MONTH>.pgn.zst', max_length=64)),
            ],
            options={
                'verbose_name': 'LICHESS Config',
                'verbose_name_plural': 'LICHESS Config',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_year', models.SmallIntegerField()),
                ('last_month', models.SmallIntegerField()),
                ('config_folder', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
