# Generated by Django 4.1.5 on 2024-08-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EloCategories',
            new_name='EloCategory',
        ),
        migrations.RenameModel(
            old_name='LichessFiles',
            new_name='LichessFile',
        ),
        migrations.AlterModelOptions(
            name='elocategory',
            options={'verbose_name': 'ELO Category', 'verbose_name_plural': 'ELO Categories'},
        ),
        migrations.AlterModelOptions(
            name='folderconfig',
            options={'verbose_name': 'Folder Configuration', 'verbose_name_plural': 'Folder Configuration'},
        ),
        migrations.AlterModelOptions(
            name='lichessfile',
            options={'verbose_name': 'LICHESS File', 'verbose_name_plural': 'LICHESS Files'},
        ),
    ]
